
name: Typeset letter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: gqcg-oss/latex-action@master
      with:
        root_file: letter.tex
        latexmk_use_xelatex: true
    - name: Archive letter.pdf
      uses: actions/upload-artifact@v2
      with:
        name: letter.pdf
        path: letter.pdf
        retention-days: 7
